#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

mkdir -p "${SCRIPT_DIR}/sky_workdir"

cp -f "${SCRIPT_DIR}/requirements.txt" "${SCRIPT_DIR}/sky_workdir/"
cp -f "${SCRIPT_DIR}/train.py" "${SCRIPT_DIR}/sky_workdir/"

echo "Files copied to sky_workdir."
