#!/usr/bin/env python

import argparse
import sys
import io
import select

from packages.wikipedia_utils import get_page_markdown_with_page_title


def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser(
        prog='wikipedia_page_md',
        description='Get the content of a specific Wikipedia page in markdown.',
    )

    parser.add_argument(
        'title', nargs='?',
        default=sys.stdin,
        help="The title of the Wikipedia page."
    )

    args = parser.parse_args(argv)

    if isinstance(args.title, io.TextIOWrapper):
        # Set a timeout for waiting for input from sys.stdin
        timeout = 2  # Timeout in seconds
        # Check if there's any input available within the timeout
        input_available, _, _ = select.select([sys.stdin], [], [], timeout)

        if input_available:
            page_title = sys.stdin.read().strip()
        else:
            print("No input provided within the timeout. Exiting. For more information, run with --help.")
            sys.exit(1)
    else:
        page_title = args.title

    print(get_page_markdown_with_page_title(page_title))


if __name__ == "__main__":
    main()
